# Generated by Django 4.1.7 on 2023-04-22 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsv', '0003_chat_alter_mark_mark_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dsv.course'),
        ),
    ]
