# Generated by Django 4.1.7 on 2023-05-01 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsv', '0004_alter_mark_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclassuser',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsv.course'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='gpa',
            field=models.FloatField(default=0),
        ),
    ]
