# Generated by Django 4.1.7 on 2023-05-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsv', '0005_myclassuser_course_alter_mark_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclassuser',
            name='course',
        ),
    ]
