# Generated by Django 4.1.7 on 2023-03-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsv', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'mark_type')},
        ),
    ]
