# Generated by Django 4.1.7 on 2023-04-02 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsv', '0002_alter_mark_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('firebase_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dsv.marktype'),
        ),
    ]
