# Generated by Django 4.1.7 on 2023-03-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsv', '0002_course_user_student_number_mark_forum_course_tutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
